name: Pierwszy workflow

on: [push]

jobs:
  pierwszy-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, World
      - run: ls
      - run: pwd
      - run: whoami
  drugi-job:
    runs-on: ubuntu-latest
    needs: [pierwszy-job]
    steps:
      - run: echo Hello, World from second job
  
